apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pleungmicrosvc
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: pleungmicrosvc
    spec:
      containers:
      - name: pleungmicrosvc
        image: peleunacr.azurecr.io/pleungmicrosvc:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pleungmicrosvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pleungmicrosvc